// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TyphoonTaskingTool.Data;

#nullable disable

namespace TyphoonTaskingTool.Migrations.Identity
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "d04e5b4c-10f0-4b2a-a25a-3fbe26f63566",
                            ConcurrencyStamp = "0165a048-fbaf-4813-97a7-055ebbaa8682",
                            Name = "user",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "9e30e59b-edd6-4cf2-b8d1-c254f43549dd",
                            ConcurrencyStamp = "5b092082-65e3-4f63-a280-884652cd6725",
                            Name = "mscuser",
                            NormalizedName = "MSCUSER"
                        },
                        new
                        {
                            Id = "bf704d5b-3971-4f86-b75e-07d625399087",
                            ConcurrencyStamp = "047c910e-dc3c-471b-a709-009ed7bb3a3e",
                            Name = "teamlead",
                            NormalizedName = "TEAMLEAD"
                        },
                        new
                        {
                            Id = "392f7177-e777-4ffc-a57d-2ed84d16ae01",
                            ConcurrencyStamp = "d6417f5d-3068-439a-ac9f-a6e1a2c2a16c",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "341b65f4-973d-4d3b-bedf-91b7da02fa56",
                            ConcurrencyStamp = "da282c34-b104-41bc-b645-dd7090f1257d",
                            Name = "coreteam",
                            NormalizedName = "CORETEAM"
                        },
                        new
                        {
                            Id = "e956e2b4-82e0-4773-ace2-d247c4d665ea",
                            ConcurrencyStamp = "4b8c80e5-44e7-4c3c-9492-292179adfbc1",
                            Name = "wssrteam",
                            NormalizedName = "WSSRTEAM"
                        },
                        new
                        {
                            Id = "b93bc257-9b6a-4049-ae24-b2c4027fe175",
                            ConcurrencyStamp = "89cd1df6-48c2-47f2-b6ce-591019534ce9",
                            Name = "tmdtteam",
                            NormalizedName = "TMDTTEAM"
                        },
                        new
                        {
                            Id = "1c47cc1b-5fe3-41a7-bd1f-9f1f421eb7ca",
                            ConcurrencyStamp = "e419c00b-9a89-4017-8230-d1361536ceaf",
                            Name = "industryteam",
                            NormalizedName = "INDUSTRYTEAM"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "a478c1b6-20aa-48e9-9abf-7e7c3bfcbd3e",
                            RoleId = "392f7177-e777-4ffc-a57d-2ed84d16ae01"
                        },
                        new
                        {
                            UserId = "418cb504-2c5d-4e58-9059-e22de9594e74",
                            RoleId = "d04e5b4c-10f0-4b2a-a25a-3fbe26f63566"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TyphoonTaskingTool.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a478c1b6-20aa-48e9-9abf-7e7c3bfcbd3e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a0095685-f76f-4498-95d4-48fc812770ec",
                            Email = "admin@finalproject.co.uk",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@FINALPROJECT.CO.UK",
                            NormalizedUserName = "ADMIN@FINALPROJECT.CO.UK",
                            PasswordHash = "AQAAAAIAAYagAAAAEBFBuieiUEt8pzM+EP8/ycCe8WQwpA0I4J4PhUsWrxsoc2eM5ODgJYym98ndGs+Hjw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8247ab4a-2085-43a3-bc0e-8f84eade514c",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = "418cb504-2c5d-4e58-9059-e22de9594e74",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5a72d2b0-dfb9-47d4-8166-176387917c46",
                            Email = "guestuser@finalproject.co.uk",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "GUESTUSER@FINALPROJECT.CO.UK",
                            NormalizedUserName = "GUESTUSER@FINALPROJECT.CO.UK",
                            PasswordHash = "AQAAAAIAAYagAAAAELYNth6ehW1UEKU63RWsqd7jsdjK80T6XQOBbZpZHiUurLaz+msveSCUUY0fkSWkkg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a02b2470-081c-4afc-be1f-886691de5cc7",
                            TwoFactorEnabled = false,
                            UserName = "guestuser"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TyphoonTaskingTool.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TyphoonTaskingTool.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TyphoonTaskingTool.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TyphoonTaskingTool.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
