// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TyphoonTaskingTool.Data;

#nullable disable

namespace TyphoonTaskingTool.Migrations.Database
{
    [DbContext(typeof(TmscDbContext))]
    [Migration("20260810134707_CreatePriorities")]
    partial class CreatePriorities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TyphoonTaskingTool.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ApplicationUser");
                });

            modelBuilder.Entity("TyphoonTaskingTool.Models.LookupPriority", b =>
                {
                    b.Property<int>("PriorityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Priority_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PriorityId"));

                    b.Property<string>("PriorityDescription")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("Priority_Description");

                    b.Property<int>("PriorityLevel")
                        .HasColumnType("integer")
                        .HasColumnName("Priority_Level");

                    b.Property<string>("PriorityLevelDescription")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Priority_Level_Description");

                    b.Property<string>("PriorityName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Priority_Name");

                    b.HasKey("PriorityId");

                    b.ToTable("LOOKUP_Priority", (string)null);

                    b.HasData(
                        new
                        {
                            PriorityId = 1,
                            PriorityDescription = "Task triaged as being High/High impact with High/Medium urgency",
                            PriorityLevel = 1,
                            PriorityLevelDescription = "24 hour response time, 48 hour resolution time",
                            PriorityName = "Critical"
                        },
                        new
                        {
                            PriorityId = 2,
                            PriorityDescription = "Task triaged as being High/Medium impact with Medium/High urgency",
                            PriorityLevel = 2,
                            PriorityLevelDescription = "48 hour response time, 5 day resolution time",
                            PriorityName = "High"
                        },
                        new
                        {
                            PriorityId = 3,
                            PriorityDescription = "Task triaged as being Low/Medium impact with High/Medium urgency",
                            PriorityLevel = 3,
                            PriorityLevelDescription = "5 day response time, 10 day resolution time",
                            PriorityName = "Medium"
                        },
                        new
                        {
                            PriorityId = 4,
                            PriorityDescription = "Task triaged as being Low impact with Medium urgency",
                            PriorityLevel = 4,
                            PriorityLevelDescription = "10 day response time, 20 day resolution time",
                            PriorityName = "Low"
                        },
                        new
                        {
                            PriorityId = 5,
                            PriorityDescription = "Routine enhancement request.",
                            PriorityLevel = 5,
                            PriorityLevelDescription = "Enhancement requests will be reviewed and prioritized based on business needs.",
                            PriorityName = "Enhancement"
                        });
                });

            modelBuilder.Entity("TyphoonTaskingTool.Models.LookupRank", b =>
                {
                    b.Property<int>("RankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Rank_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RankId"));

                    b.Property<string>("RankNameLong")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Rank_NameLong");

                    b.Property<string>("RankNameShort")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Rank_NameShort");

                    b.Property<string>("RankNatoequiv")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Rank_NATOEquiv");

                    b.HasKey("RankId");

                    b.ToTable("LOOKUP_Rank", (string)null);

                    b.HasData(
                        new
                        {
                            RankId = 1,
                            RankNameLong = "Air Recruit",
                            RankNameShort = "AR",
                            RankNatoequiv = "OR-1"
                        },
                        new
                        {
                            RankId = 4,
                            RankNameLong = "Air Specialist 2",
                            RankNameShort = "AS2",
                            RankNatoequiv = "OR-2"
                        },
                        new
                        {
                            RankId = 7,
                            RankNameLong = "Air Specialist 1",
                            RankNameShort = "AS1",
                            RankNatoequiv = "OR-2"
                        },
                        new
                        {
                            RankId = 10,
                            RankNameLong = "Air Specialist 1 (Technician)",
                            RankNameShort = "AS1(T)",
                            RankNatoequiv = "OR-2"
                        },
                        new
                        {
                            RankId = 13,
                            RankNameLong = "Lance Corporal",
                            RankNameShort = "LCpl",
                            RankNatoequiv = "OR-3"
                        },
                        new
                        {
                            RankId = 16,
                            RankNameLong = "Corporal",
                            RankNameShort = "Cpl",
                            RankNatoequiv = "OR-4"
                        },
                        new
                        {
                            RankId = 19,
                            RankNameLong = "Sergeant",
                            RankNameShort = "Sgt",
                            RankNatoequiv = "OR-6"
                        },
                        new
                        {
                            RankId = 22,
                            RankNameLong = "Chief Technician",
                            RankNameShort = "CT",
                            RankNatoequiv = "OR-7"
                        },
                        new
                        {
                            RankId = 25,
                            RankNameLong = "Flight Sergeant",
                            RankNameShort = "FS",
                            RankNatoequiv = "OR-7"
                        },
                        new
                        {
                            RankId = 28,
                            RankNameLong = "Warrant Officer / Master Aircrew",
                            RankNameShort = "WO/MAcr",
                            RankNatoequiv = "OR-9"
                        },
                        new
                        {
                            RankId = 41,
                            RankNameLong = "Pilot Officer",
                            RankNameShort = "PO",
                            RankNatoequiv = "OF-1"
                        },
                        new
                        {
                            RankId = 44,
                            RankNameLong = "Flying Officer",
                            RankNameShort = "FO",
                            RankNatoequiv = "OF-1"
                        },
                        new
                        {
                            RankId = 47,
                            RankNameLong = "Flight Lieutenant",
                            RankNameShort = "Flt Lt",
                            RankNatoequiv = "OF-2"
                        },
                        new
                        {
                            RankId = 50,
                            RankNameLong = "Squadron Leader",
                            RankNameShort = "Sqn Ldr",
                            RankNatoequiv = "OF-3"
                        },
                        new
                        {
                            RankId = 53,
                            RankNameLong = "Wing Commander",
                            RankNameShort = "Wg Cdr",
                            RankNatoequiv = "OF-4"
                        },
                        new
                        {
                            RankId = 56,
                            RankNameLong = "Group Captain",
                            RankNameShort = "Gp Capt",
                            RankNatoequiv = "OF-5"
                        },
                        new
                        {
                            RankId = 59,
                            RankNameLong = "Air Commodore",
                            RankNameShort = "Air Cmdre",
                            RankNatoequiv = "OF-6"
                        },
                        new
                        {
                            RankId = 62,
                            RankNameLong = "Air Vice Marshall",
                            RankNameShort = "AVM",
                            RankNatoequiv = "OF-7"
                        },
                        new
                        {
                            RankId = 65,
                            RankNameLong = "Air Marshall",
                            RankNameShort = "AM",
                            RankNatoequiv = "OF-8"
                        },
                        new
                        {
                            RankId = 68,
                            RankNameLong = "Air Chief Marshall",
                            RankNameShort = "ACM",
                            RankNatoequiv = "OF-9"
                        },
                        new
                        {
                            RankId = 71,
                            RankNameLong = "Marshall of the Royal Air Force",
                            RankNameShort = "MRAF",
                            RankNatoequiv = "OF-10"
                        });
                });

            modelBuilder.Entity("TyphoonTaskingTool.Models.LookupStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Status_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StatusId"));

                    b.Property<string>("StatusDescription")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("Status_Description");

                    b.Property<string>("StatusName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Status_Name");

                    b.HasKey("StatusId");

                    b.ToTable("LOOKUP_Status", (string)null);

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            StatusDescription = "The task has been submitted .",
                            StatusName = "Submitted"
                        },
                        new
                        {
                            StatusId = 2,
                            StatusDescription = "The task is active and ongoing.",
                            StatusName = "Active"
                        },
                        new
                        {
                            StatusId = 3,
                            StatusDescription = "The task has been completed successfully.",
                            StatusName = "Completed"
                        },
                        new
                        {
                            StatusId = 4,
                            StatusDescription = "The task is temporarily paused and awaiting further action.",
                            StatusName = "On Hold"
                        },
                        new
                        {
                            StatusId = 5,
                            StatusDescription = "The task has been cancelled and will not be completed.",
                            StatusName = "Cancelled"
                        },
                        new
                        {
                            StatusId = 6,
                            StatusDescription = "The task is currently in progress and being worked on.",
                            StatusName = "In Progress"
                        });
                });

            modelBuilder.Entity("TyphoonTaskingTool.Models.LookupTeam", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Team_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TeamId"));

                    b.Property<string>("TeamNameLong")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("Team_NameLong");

                    b.Property<string>("TeamNameShort")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Team_NameShort");

                    b.HasKey("TeamId");

                    b.ToTable("LOOKUP_Team", (string)null);

                    b.HasData(
                        new
                        {
                            TeamId = 1001,
                            TeamNameLong = "Information Exploitation and Technology Support",
                            TeamNameShort = "IxTS"
                        },
                        new
                        {
                            TeamId = 1005,
                            TeamNameLong = "Data Management",
                            TeamNameShort = "DM"
                        },
                        new
                        {
                            TeamId = 1009,
                            TeamNameLong = "Typhoon Mission Data Team",
                            TeamNameShort = "TMDT"
                        },
                        new
                        {
                            TeamId = 1013,
                            TeamNameLong = "Industry Specialists",
                            TeamNameShort = "Ind Spec"
                        },
                        new
                        {
                            TeamId = 1017,
                            TeamNameLong = "Mission Data Analysis Team",
                            TeamNameShort = "MDAT"
                        },
                        new
                        {
                            TeamId = 1021,
                            TeamNameLong = "Attack and Identification",
                            TeamNameShort = "A and I"
                        },
                        new
                        {
                            TeamId = 1026,
                            TeamNameLong = "Management",
                            TeamNameShort = "Mgmnt"
                        });
                });

            modelBuilder.Entity("TyphoonTaskingTool.Models.LookupTrafficLight", b =>
                {
                    b.Property<int>("trafficLightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("TrafficLightID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("trafficLightId"));

                    b.Property<string>("trafficLightDescription")
                        .HasColumnType("text")
                        .HasColumnName("TrafficLightDescription");

                    b.Property<string>("trafficLightName")
                        .HasColumnType("text")
                        .HasColumnName("TrafficLightName");

                    b.HasKey("trafficLightId");

                    b.ToTable("LOOKUP_TrafficLight", (string)null);

                    b.HasData(
                        new
                        {
                            trafficLightId = 1,
                            trafficLightDescription = "Not Required",
                            trafficLightName = "BLANK"
                        },
                        new
                        {
                            trafficLightId = 2,
                            trafficLightDescription = "Desirable",
                            trafficLightName = "YELLOW"
                        },
                        new
                        {
                            trafficLightId = 3,
                            trafficLightDescription = "Highly Desirable",
                            trafficLightName = "AMBER"
                        },
                        new
                        {
                            trafficLightId = 4,
                            trafficLightDescription = "Essential",
                            trafficLightName = "RED"
                        });
                });

            modelBuilder.Entity("TyphoonTaskingTool.Models.LookupUnit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Unit_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UnitId"));

                    b.Property<string>("UnitNameLong")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("Unit_NameLong");

                    b.Property<string>("UnitNameShort")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Unit_NameShort");

                    b.HasKey("UnitId");

                    b.ToTable("LOOKUP_Unit", (string)null);

                    b.HasData(
                        new
                        {
                            UnitId = 5001,
                            UnitNameLong = "Number 3 (Fighter) Squadron",
                            UnitNameShort = "3(F) Sqn"
                        },
                        new
                        {
                            UnitId = 5003,
                            UnitNameLong = "Number 11 (Fighter) Squadron",
                            UnitNameShort = "XI (F) Sqn"
                        },
                        new
                        {
                            UnitId = 5006,
                            UnitNameLong = "Number 12 Squadron",
                            UnitNameShort = "12 Sqn"
                        },
                        new
                        {
                            UnitId = 5009,
                            UnitNameLong = "Number 29 Squadron",
                            UnitNameShort = "29 Sqn"
                        },
                        new
                        {
                            UnitId = 5012,
                            UnitNameLong = "Number 41 (Test and Evaluation) Squadron",
                            UnitNameShort = "41 (TES) Sqn"
                        },
                        new
                        {
                            UnitId = 5015,
                            UnitNameLong = "Typhoon National Support Centre",
                            UnitNameShort = "Ty NSC"
                        },
                        new
                        {
                            UnitId = 5018,
                            UnitNameLong = "Typhoon Mission Support Centre",
                            UnitNameShort = "Ty MSC"
                        },
                        new
                        {
                            UnitId = 5021,
                            UnitNameLong = "Typhoon CAMO",
                            UnitNameShort = "Ty CAMO"
                        },
                        new
                        {
                            UnitId = 5024,
                            UnitNameLong = "Air & Space Warfare Centre",
                            UnitNameShort = "ASWC"
                        },
                        new
                        {
                            UnitId = 5027,
                            UnitNameLong = "Typhoon Force Headquarters",
                            UnitNameShort = "Ty FHQ"
                        },
                        new
                        {
                            UnitId = 5030,
                            UnitNameLong = "Any Other External Organisation",
                            UnitNameShort = "Others"
                        });
                });

            modelBuilder.Entity("TyphoonTaskingTool.Models.Request", b =>
                {
                    b.Property<Guid>("RequestTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Request_TaskId")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int?>("RankId")
                        .HasColumnType("integer")
                        .HasColumnName("Rank_Id");

                    b.Property<bool?>("RequestArchive")
                        .HasColumnType("boolean")
                        .HasColumnName("Request_Archive");

                    b.Property<string>("RequestContactPhone")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("Request_ContactPhone");

                    b.Property<DateTime?>("RequestCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Request_Created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("RequestEmailAdd")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("Request_EmailAdd");

                    b.Property<string>("RequestFirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Request_FirstName");

                    b.Property<string>("RequestLastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Request_LastName");

                    b.Property<string>("RequestShortId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("Request_ShortId");

                    b.Property<string>("RequestTaskDescription")
                        .HasColumnType("text")
                        .HasColumnName("Request_TaskDescription");

                    b.Property<string>("RequestTitle")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("Request_Title");

                    b.Property<int?>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("Status_Id");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("Team_Id");

                    b.Property<int?>("UnitId")
                        .HasColumnType("integer")
                        .HasColumnName("Unit_Id");

                    b.HasKey("RequestTaskId");

                    b.HasIndex("RankId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TeamId");

                    b.HasIndex("UnitId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("TyphoonTaskingTool.Models.RequestUpdate", b =>
                {
                    b.Property<Guid>("UpdateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Update_Id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AssignmentUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("Assignment_UserId");

                    b.Property<int?>("PriorityId")
                        .HasColumnType("integer");

                    b.Property<Guid>("RequestTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("Request_TaskId");

                    b.Property<int?>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("Status_Id");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("Team_Id");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Update_By");

                    b.Property<string>("UpdateDescription")
                        .HasColumnType("text")
                        .HasColumnName("Update_Description");

                    b.Property<DateTime?>("UpdateTimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Update_TimeStamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UpdateId");

                    b.HasIndex("AssignmentUserId");

                    b.HasIndex("PriorityId");

                    b.HasIndex("RequestTaskId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TeamId");

                    b.ToTable("RequestUpdates");
                });

            modelBuilder.Entity("TyphoonTaskingTool.Models.RigRequest", b =>
                {
                    b.Property<Guid>("rigRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Rig_Request_Id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("rigCcbCompelte")
                        .HasColumnType("boolean");

                    b.Property<string>("rigCcbRefernce")
                        .HasColumnType("text");

                    b.Property<string>("rigRequestAdditionalMD")
                        .HasColumnType("text");

                    b.Property<string>("rigRequestAddtionalRig")
                        .HasColumnType("text");

                    b.Property<bool?>("rigRequestArchive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("rigRequestCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Rig_Request_Created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("rigRequestDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("rigRequestEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("rigRequestName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("Rig_Request_Name");

                    b.Property<int?>("rigRequestRankId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("rigRequestStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("rigRequestTitle")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("Rig_Request_Title");

                    b.Property<int?>("statusId")
                        .HasColumnType("integer")
                        .HasColumnName("Status_Id");

                    b.HasKey("rigRequestId");

                    b.ToTable("RigRequests");
                });

            modelBuilder.Entity("TyphoonTaskingTool.Models.RigRequestModels.AdditionalSystems", b =>
                {
                    b.Property<Guid>("rigRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("requestrigRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("rigRequestId");

                    b.HasIndex("requestrigRequestId");

                    b.ToTable("AdditionalSystems");
                });

            modelBuilder.Entity("TyphoonTaskingTool.Models.RigRequestModels.CriticalLRIs", b =>
                {
                    b.Property<Guid>("rigRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("requestrigRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("rigRequestId");

                    b.HasIndex("requestrigRequestId");

                    b.ToTable("CriticalLRIs");
                });

            modelBuilder.Entity("TyphoonTaskingTool.Models.RigRequestModels.DataRecording", b =>
                {
                    b.Property<Guid>("rigRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("requestrigRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("rigRequestId");

                    b.HasIndex("requestrigRequestId");

                    b.ToTable("DataRecording");
                });

            modelBuilder.Entity("TyphoonTaskingTool.Models.RigRequestModels.LookupStores", b =>
                {
                    b.Property<int>("StoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Store_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StoreId"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("Image_Url");

                    b.Property<string>("StoreDescription")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("Store_Description");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Store_Name");

                    b.HasKey("StoreId");

                    b.ToTable("LOOKUP_Stores", (string)null);

                    b.HasData(
                        new
                        {
                            StoreId = 101,
                            ImageUrl = "images/A2A/AMRAAM_120_B5.png",
                            StoreDescription = "Description for Store A",
                            StoreName = "AMRAAM 120 B5"
                        },
                        new
                        {
                            StoreId = 102,
                            ImageUrl = "images/A2A/AMRAAM_120-D.png",
                            StoreDescription = "Description for Store A",
                            StoreName = "AMRAAM 120 D"
                        },
                        new
                        {
                            StoreId = 103,
                            ImageUrl = "images/A2A/AMRAAM_120M-C5.png",
                            StoreDescription = "Description for Store A",
                            StoreName = "AMRAAM 120M C5"
                        },
                        new
                        {
                            StoreId = 104,
                            ImageUrl = "images/A2A/AMRAAM_120M-C5_AAVI.png",
                            StoreDescription = "Description for Store A",
                            StoreName = "AMRAAM 120M C5 AAVI"
                        },
                        new
                        {
                            StoreId = 105,
                            ImageUrl = "images/A2A/AMRAAM_OM.png",
                            StoreDescription = "Description for Store A",
                            StoreName = "AMRAAM 120 OM"
                        },
                        new
                        {
                            StoreId = 106,
                            ImageUrl = "images/A2A/ASRAAM_TOM.png",
                            StoreDescription = "Description for Store A",
                            StoreName = "ASRAAM TOM"
                        },
                        new
                        {
                            StoreId = 201,
                            ImageUrl = "images/A2A/BS2_STN_3_Empty.png",
                            StoreDescription = "Description for Store A",
                            StoreName = "BS STN 3 Empty"
                        },
                        new
                        {
                            StoreId = 202,
                            ImageUrl = "images/A2A/BS2_STN_4_Empty.png",
                            StoreDescription = "Description for Store A",
                            StoreName = "BS STN 4 Empty"
                        },
                        new
                        {
                            StoreId = 203,
                            ImageUrl = "images/A2A/BS2_EDGM.png",
                            StoreDescription = "Description for Store A",
                            StoreName = "BS 2 EDGM"
                        },
                        new
                        {
                            StoreId = 204,
                            ImageUrl = "images/A2A/BS2_OM.png",
                            StoreDescription = "Description for Store A",
                            StoreName = "BS 2 OM"
                        },
                        new
                        {
                            StoreId = 205,
                            ImageUrl = "images/A2A/BS2_TOM.png",
                            StoreDescription = "Description for Store A",
                            StoreName = "BS 2 TOM"
                        });
                });

            modelBuilder.Entity("TyphoonTaskingTool.Models.RigRequestModels.MissionPlanning", b =>
                {
                    b.Property<Guid>("rigRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("requestrigRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("rigRequestId");

                    b.HasIndex("requestrigRequestId");

                    b.ToTable("MissionPlanning");
                });

            modelBuilder.Entity("TyphoonTaskingTool.Models.RigRequestModels.RigSetup", b =>
                {
                    b.Property<Guid>("rigRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("requestrigRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("rigRequestId");

                    b.HasIndex("requestrigRequestId");

                    b.ToTable("RigSetup");
                });

            modelBuilder.Entity("TyphoonTaskingTool.Models.Request", b =>
                {
                    b.HasOne("TyphoonTaskingTool.Models.LookupRank", "Rank")
                        .WithMany("Requests")
                        .HasForeignKey("RankId")
                        .HasConstraintName("FK_Request_Rank");

                    b.HasOne("TyphoonTaskingTool.Models.LookupStatus", "Status")
                        .WithMany("Requests")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("FK_Request_Status");

                    b.HasOne("TyphoonTaskingTool.Models.LookupTeam", "Team")
                        .WithMany("Requests")
                        .HasForeignKey("TeamId")
                        .HasConstraintName("FK_Request_Team");

                    b.HasOne("TyphoonTaskingTool.Models.LookupUnit", "Unit")
                        .WithMany("Requests")
                        .HasForeignKey("UnitId")
                        .HasConstraintName("FK_Request_Unit");

                    b.Navigation("Rank");

                    b.Navigation("Status");

                    b.Navigation("Team");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("TyphoonTaskingTool.Models.RequestUpdate", b =>
                {
                    b.HasOne("TyphoonTaskingTool.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("AssignmentUserId")
                        .HasConstraintName("FK_UpdateAssignedUser");

                    b.HasOne("TyphoonTaskingTool.Models.LookupPriority", "Priority")
                        .WithMany()
                        .HasForeignKey("PriorityId");

                    b.HasOne("TyphoonTaskingTool.Models.Request", "RequestTask")
                        .WithMany("RequestUpdates")
                        .HasForeignKey("RequestTaskId")
                        .IsRequired()
                        .HasConstraintName("FK_UpdateRequest");

                    b.HasOne("TyphoonTaskingTool.Models.LookupStatus", "Status")
                        .WithMany("RequestUpdates")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("FK_UpdateStatus");

                    b.HasOne("TyphoonTaskingTool.Models.LookupTeam", "Team")
                        .WithMany("RequestUpdates")
                        .HasForeignKey("TeamId")
                        .HasConstraintName("FK_UpdateTeam");

                    b.Navigation("Priority");

                    b.Navigation("RequestTask");

                    b.Navigation("Status");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("TyphoonTaskingTool.Models.RigRequestModels.AdditionalSystems", b =>
                {
                    b.HasOne("TyphoonTaskingTool.Models.RigRequest", "request")
                        .WithMany()
                        .HasForeignKey("requestrigRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TyphoonTaskingTool.Components.RigRequestSetupField", "additionalSystem_Asraam_Em", b1 =>
                        {
                            b1.Property<Guid>("AdditionalSystemsrigRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .HasColumnType("text")
                                .HasColumnName("additionalSystem_Asraam_Em");

                            b1.Property<int?>("trafficLightId")
                                .HasColumnType("integer")
                                .HasColumnName("additionalSystem_Asraam_Em_TrafficLightId");

                            b1.HasKey("AdditionalSystemsrigRequestId");

                            b1.ToTable("AdditionalSystems");

                            b1.WithOwner()
                                .HasForeignKey("AdditionalSystemsrigRequestId");
                        });

                    b.OwnsOne("TyphoonTaskingTool.Components.RigRequestSetupField", "additionalSystem_B2_Em", b1 =>
                        {
                            b1.Property<Guid>("AdditionalSystemsrigRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .HasColumnType("text")
                                .HasColumnName("additionalSystem_B2_Em");

                            b1.Property<int?>("trafficLightId")
                                .HasColumnType("integer")
                                .HasColumnName("additionalSystem_B2_Em_TrafficLightId");

                            b1.HasKey("AdditionalSystemsrigRequestId");

                            b1.ToTable("AdditionalSystems");

                            b1.WithOwner()
                                .HasForeignKey("AdditionalSystemsrigRequestId");
                        });

                    b.OwnsOne("TyphoonTaskingTool.Components.RigRequestSetupField", "additionalSystem_Meteor_Em", b1 =>
                        {
                            b1.Property<Guid>("AdditionalSystemsrigRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .HasColumnType("text")
                                .HasColumnName("additionalSystem_Meteor_Em");

                            b1.Property<int?>("trafficLightId")
                                .HasColumnType("integer")
                                .HasColumnName("additionalSystem_Meteor_Em_TrafficLightId");

                            b1.HasKey("AdditionalSystemsrigRequestId");

                            b1.ToTable("AdditionalSystems");

                            b1.WithOwner()
                                .HasForeignKey("AdditionalSystemsrigRequestId");
                        });

                    b.OwnsOne("TyphoonTaskingTool.Components.RigRequestSetupField", "additionalSystem_Mids_Tiger", b1 =>
                        {
                            b1.Property<Guid>("AdditionalSystemsrigRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .HasColumnType("text")
                                .HasColumnName("additionalSystem_Mids_Tiger");

                            b1.Property<int?>("trafficLightId")
                                .HasColumnType("integer")
                                .HasColumnName("additionalSystem_Mids_Tiger_TrafficLightId");

                            b1.HasKey("AdditionalSystemsrigRequestId");

                            b1.ToTable("AdditionalSystems");

                            b1.WithOwner()
                                .HasForeignKey("AdditionalSystemsrigRequestId");
                        });

                    b.OwnsOne("TyphoonTaskingTool.Components.RigRequestSetupField", "additionalSystem_Pasis", b1 =>
                        {
                            b1.Property<Guid>("AdditionalSystemsrigRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .HasColumnType("text")
                                .HasColumnName("additionalSystem_Pasis");

                            b1.Property<int?>("trafficLightId")
                                .HasColumnType("integer")
                                .HasColumnName("additionalSystem_Pasis_TrafficLightId");

                            b1.HasKey("AdditionalSystemsrigRequestId");

                            b1.ToTable("AdditionalSystems");

                            b1.WithOwner()
                                .HasForeignKey("AdditionalSystemsrigRequestId");
                        });

                    b.OwnsOne("TyphoonTaskingTool.Components.RigRequestSetupField", "additionalSystem_SS_Em", b1 =>
                        {
                            b1.Property<Guid>("AdditionalSystemsrigRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .HasColumnType("text")
                                .HasColumnName("additionalSystem_SS_Em");

                            b1.Property<int?>("trafficLightId")
                                .HasColumnType("integer")
                                .HasColumnName("additionalSystem_SS_Em_TrafficLightId");

                            b1.HasKey("AdditionalSystemsrigRequestId");

                            b1.ToTable("AdditionalSystems");

                            b1.WithOwner()
                                .HasForeignKey("AdditionalSystemsrigRequestId");
                        });

                    b.Navigation("additionalSystem_Asraam_Em")
                        .IsRequired();

                    b.Navigation("additionalSystem_B2_Em")
                        .IsRequired();

                    b.Navigation("additionalSystem_Meteor_Em")
                        .IsRequired();

                    b.Navigation("additionalSystem_Mids_Tiger")
                        .IsRequired();

                    b.Navigation("additionalSystem_Pasis")
                        .IsRequired();

                    b.Navigation("additionalSystem_SS_Em")
                        .IsRequired();

                    b.Navigation("request");
                });

            modelBuilder.Entity("TyphoonTaskingTool.Models.RigRequestModels.CriticalLRIs", b =>
                {
                    b.HasOne("TyphoonTaskingTool.Models.RigRequest", "request")
                        .WithMany()
                        .HasForeignKey("requestrigRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TyphoonTaskingTool.Components.RigRequestSetupField", "criticalLRI_Gps", b1 =>
                        {
                            b1.Property<Guid>("CriticalLRIsrigRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .HasColumnType("text")
                                .HasColumnName("criticalLRI_Gps");

                            b1.Property<int?>("trafficLightId")
                                .HasColumnType("integer")
                                .HasColumnName("criticalLRI_Gps_TrafficLightId");

                            b1.HasKey("CriticalLRIsrigRequestId");

                            b1.ToTable("CriticalLRIs");

                            b1.WithOwner()
                                .HasForeignKey("CriticalLRIsrigRequestId");
                        });

                    b.OwnsOne("TyphoonTaskingTool.Components.RigRequestSetupField", "criticalLRI_Mids", b1 =>
                        {
                            b1.Property<Guid>("CriticalLRIsrigRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .HasColumnType("text")
                                .HasColumnName("criticalLRI_Mids");

                            b1.Property<int?>("trafficLightId")
                                .HasColumnType("integer")
                                .HasColumnName("criticalLRI_Mids_TrafficLightId");

                            b1.HasKey("CriticalLRIsrigRequestId");

                            b1.ToTable("CriticalLRIs");

                            b1.WithOwner()
                                .HasForeignKey("CriticalLRIsrigRequestId");
                        });

                    b.OwnsOne("TyphoonTaskingTool.Components.RigRequestSetupField", "criticalLRI_Other", b1 =>
                        {
                            b1.Property<Guid>("CriticalLRIsrigRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .HasColumnType("text")
                                .HasColumnName("criticalLRI_Other");

                            b1.Property<int?>("trafficLightId")
                                .HasColumnType("integer")
                                .HasColumnName("criticalLRI_Other_TrafficLightId");

                            b1.HasKey("CriticalLRIsrigRequestId");

                            b1.ToTable("CriticalLRIs");

                            b1.WithOwner()
                                .HasForeignKey("CriticalLRIsrigRequestId");
                        });

                    b.OwnsOne("TyphoonTaskingTool.Components.RigRequestSetupField", "criticalLRI_Radar", b1 =>
                        {
                            b1.Property<Guid>("CriticalLRIsrigRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .HasColumnType("text")
                                .HasColumnName("criticalLRI_Radar");

                            b1.Property<int?>("trafficLightId")
                                .HasColumnType("integer")
                                .HasColumnName("criticalLRI_Radar_TrafficLightId");

                            b1.HasKey("CriticalLRIsrigRequestId");

                            b1.ToTable("CriticalLRIs");

                            b1.WithOwner()
                                .HasForeignKey("CriticalLRIsrigRequestId");
                        });

                    b.Navigation("criticalLRI_Gps")
                        .IsRequired();

                    b.Navigation("criticalLRI_Mids")
                        .IsRequired();

                    b.Navigation("criticalLRI_Other")
                        .IsRequired();

                    b.Navigation("criticalLRI_Radar")
                        .IsRequired();

                    b.Navigation("request");
                });

            modelBuilder.Entity("TyphoonTaskingTool.Models.RigRequestModels.DataRecording", b =>
                {
                    b.HasOne("TyphoonTaskingTool.Models.RigRequest", "request")
                        .WithMany()
                        .HasForeignKey("requestrigRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TyphoonTaskingTool.Components.RigRequestSetupField", "additionalRecording", b1 =>
                        {
                            b1.Property<Guid>("DataRecordingrigRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .HasColumnType("text")
                                .HasColumnName("additionalRecording");

                            b1.Property<int?>("trafficLightId")
                                .HasColumnType("integer")
                                .HasColumnName("additionalRecording_TrafficLightId");

                            b1.HasKey("DataRecordingrigRequestId");

                            b1.ToTable("DataRecording");

                            b1.WithOwner()
                                .HasForeignKey("DataRecordingrigRequestId");
                        });

                    b.OwnsOne("TyphoonTaskingTool.Components.RigRequestSetupField", "mhdd", b1 =>
                        {
                            b1.Property<Guid>("DataRecordingrigRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .HasColumnType("text")
                                .HasColumnName("mhdd");

                            b1.Property<int?>("trafficLightId")
                                .HasColumnType("integer")
                                .HasColumnName("mhdd_TrafficLightId");

                            b1.HasKey("DataRecordingrigRequestId");

                            b1.ToTable("DataRecording");

                            b1.WithOwner()
                                .HasForeignKey("DataRecordingrigRequestId");
                        });

                    b.OwnsOne("TyphoonTaskingTool.Components.RigRequestSetupField", "recording_1", b1 =>
                        {
                            b1.Property<Guid>("DataRecordingrigRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .HasColumnType("text")
                                .HasColumnName("recording_1");

                            b1.Property<int?>("trafficLightId")
                                .HasColumnType("integer")
                                .HasColumnName("recording_1_TrafficLightId");

                            b1.HasKey("DataRecordingrigRequestId");

                            b1.ToTable("DataRecording");

                            b1.WithOwner()
                                .HasForeignKey("DataRecordingrigRequestId");
                        });

                    b.OwnsOne("TyphoonTaskingTool.Components.RigRequestSetupField", "recording_2", b1 =>
                        {
                            b1.Property<Guid>("DataRecordingrigRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .HasColumnType("text")
                                .HasColumnName("recording_2");

                            b1.Property<int?>("trafficLightId")
                                .HasColumnType("integer")
                                .HasColumnName("recording_2_TrafficLightId");

                            b1.HasKey("DataRecordingrigRequestId");

                            b1.ToTable("DataRecording");

                            b1.WithOwner()
                                .HasForeignKey("DataRecordingrigRequestId");
                        });

                    b.OwnsOne("TyphoonTaskingTool.Components.RigRequestSetupField", "recording_3", b1 =>
                        {
                            b1.Property<Guid>("DataRecordingrigRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .HasColumnType("text")
                                .HasColumnName("recording_3");

                            b1.Property<int?>("trafficLightId")
                                .HasColumnType("integer")
                                .HasColumnName("recording_3_TrafficLightId");

                            b1.HasKey("DataRecordingrigRequestId");

                            b1.ToTable("DataRecording");

                            b1.WithOwner()
                                .HasForeignKey("DataRecordingrigRequestId");
                        });

                    b.OwnsOne("TyphoonTaskingTool.Components.RigRequestSetupField", "recording_4", b1 =>
                        {
                            b1.Property<Guid>("DataRecordingrigRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .HasColumnType("text")
                                .HasColumnName("recording_4");

                            b1.Property<int?>("trafficLightId")
                                .HasColumnType("integer")
                                .HasColumnName("recording_4_TrafficLightId");

                            b1.HasKey("DataRecordingrigRequestId");

                            b1.ToTable("DataRecording");

                            b1.WithOwner()
                                .HasForeignKey("DataRecordingrigRequestId");
                        });

                    b.OwnsOne("TyphoonTaskingTool.Components.RigRequestSetupField", "recording_5", b1 =>
                        {
                            b1.Property<Guid>("DataRecordingrigRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .HasColumnType("text")
                                .HasColumnName("recording_5");

                            b1.Property<int?>("trafficLightId")
                                .HasColumnType("integer")
                                .HasColumnName("recording_5_TrafficLightId");

                            b1.HasKey("DataRecordingrigRequestId");

                            b1.ToTable("DataRecording");

                            b1.WithOwner()
                                .HasForeignKey("DataRecordingrigRequestId");
                        });

                    b.OwnsOne("TyphoonTaskingTool.Components.RigRequestSetupField", "recording_6", b1 =>
                        {
                            b1.Property<Guid>("DataRecordingrigRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .HasColumnType("text")
                                .HasColumnName("recording_6");

                            b1.Property<int?>("trafficLightId")
                                .HasColumnType("integer")
                                .HasColumnName("recording_6_TrafficLightId");

                            b1.HasKey("DataRecordingrigRequestId");

                            b1.ToTable("DataRecording");

                            b1.WithOwner()
                                .HasForeignKey("DataRecordingrigRequestId");
                        });

                    b.Navigation("additionalRecording")
                        .IsRequired();

                    b.Navigation("mhdd")
                        .IsRequired();

                    b.Navigation("recording_1")
                        .IsRequired();

                    b.Navigation("recording_2")
                        .IsRequired();

                    b.Navigation("recording_3")
                        .IsRequired();

                    b.Navigation("recording_4")
                        .IsRequired();

                    b.Navigation("recording_5")
                        .IsRequired();

                    b.Navigation("recording_6")
                        .IsRequired();

                    b.Navigation("request");
                });

            modelBuilder.Entity("TyphoonTaskingTool.Models.RigRequestModels.MissionPlanning", b =>
                {
                    b.HasOne("TyphoonTaskingTool.Models.RigRequest", "request")
                        .WithMany()
                        .HasForeignKey("requestrigRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TyphoonTaskingTool.Components.RigRequestSetupField", "MissionPlanning_Geo_Location", b1 =>
                        {
                            b1.Property<Guid>("MissionPlanningrigRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .HasColumnType("text")
                                .HasColumnName("MissionPlanning_Geo_Location");

                            b1.Property<int?>("trafficLightId")
                                .HasColumnType("integer")
                                .HasColumnName("MissionPlanning_Geo_Location_TrafficLightId");

                            b1.HasKey("MissionPlanningrigRequestId");

                            b1.ToTable("MissionPlanning");

                            b1.WithOwner()
                                .HasForeignKey("MissionPlanningrigRequestId");
                        });

                    b.OwnsOne("TyphoonTaskingTool.Components.RigRequestSetupField", "missionPlanning_L16_IDS", b1 =>
                        {
                            b1.Property<Guid>("MissionPlanningrigRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .HasColumnType("text")
                                .HasColumnName("missionPlanning_L16_IDS");

                            b1.Property<int?>("trafficLightId")
                                .HasColumnType("integer")
                                .HasColumnName("missionPlanning_L16_IDS_TrafficLightId");

                            b1.HasKey("MissionPlanningrigRequestId");

                            b1.ToTable("MissionPlanning");

                            b1.WithOwner()
                                .HasForeignKey("MissionPlanningrigRequestId");
                        });

                    b.OwnsOne("TyphoonTaskingTool.Components.RigRequestSetupField", "missionPlanning_L16_Ntwk", b1 =>
                        {
                            b1.Property<Guid>("MissionPlanningrigRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .HasColumnType("text")
                                .HasColumnName("missionPlanning_L16_Ntwk");

                            b1.Property<int?>("trafficLightId")
                                .HasColumnType("integer")
                                .HasColumnName("missionPlanning_L16_Ntwk_TrafficLightId");

                            b1.HasKey("MissionPlanningrigRequestId");

                            b1.ToTable("MissionPlanning");

                            b1.WithOwner()
                                .HasForeignKey("MissionPlanningrigRequestId");
                        });

                    b.OwnsOne("TyphoonTaskingTool.Components.RigRequestSetupField", "missionPlanning_Maps", b1 =>
                        {
                            b1.Property<Guid>("MissionPlanningrigRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .HasColumnType("text")
                                .HasColumnName("missionPlanning_Maps");

                            b1.Property<int?>("trafficLightId")
                                .HasColumnType("integer")
                                .HasColumnName("missionPlanning_Maps_TrafficLightId");

                            b1.HasKey("MissionPlanningrigRequestId");

                            b1.ToTable("MissionPlanning");

                            b1.WithOwner()
                                .HasForeignKey("MissionPlanningrigRequestId");
                        });

                    b.OwnsOne("TyphoonTaskingTool.Components.RigRequestSetupField", "missionPlanning_MissionType", b1 =>
                        {
                            b1.Property<Guid>("MissionPlanningrigRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .HasColumnType("text")
                                .HasColumnName("missionPlanning_MissionType");

                            b1.Property<int?>("trafficLightId")
                                .HasColumnType("integer")
                                .HasColumnName("missionPlanning_MissionType_TrafficLightId");

                            b1.HasKey("MissionPlanningrigRequestId");

                            b1.ToTable("MissionPlanning");

                            b1.WithOwner()
                                .HasForeignKey("MissionPlanningrigRequestId");
                        });

                    b.OwnsOne("TyphoonTaskingTool.Components.RigRequestSetupField", "missionPlanning_Ss_Mission_File", b1 =>
                        {
                            b1.Property<Guid>("MissionPlanningrigRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .HasColumnType("text")
                                .HasColumnName("missionPlanning_Ss_Mission_File");

                            b1.Property<int?>("trafficLightId")
                                .HasColumnType("integer")
                                .HasColumnName("missionPlanning_Ss_Mission_File_TrafficLightId");

                            b1.HasKey("MissionPlanningrigRequestId");

                            b1.ToTable("MissionPlanning");

                            b1.WithOwner()
                                .HasForeignKey("MissionPlanningrigRequestId");
                        });

                    b.Navigation("MissionPlanning_Geo_Location")
                        .IsRequired();

                    b.Navigation("missionPlanning_L16_IDS")
                        .IsRequired();

                    b.Navigation("missionPlanning_L16_Ntwk")
                        .IsRequired();

                    b.Navigation("missionPlanning_Maps")
                        .IsRequired();

                    b.Navigation("missionPlanning_MissionType")
                        .IsRequired();

                    b.Navigation("missionPlanning_Ss_Mission_File")
                        .IsRequired();

                    b.Navigation("request");
                });

            modelBuilder.Entity("TyphoonTaskingTool.Models.RigRequestModels.RigSetup", b =>
                {
                    b.HasOne("TyphoonTaskingTool.Models.RigRequest", "request")
                        .WithMany()
                        .HasForeignKey("requestrigRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TyphoonTaskingTool.Components.RigRequestSetupField", "rigSetup_Avionic_Std", b1 =>
                        {
                            b1.Property<Guid>("RigSetuprigRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .HasColumnType("text")
                                .HasColumnName("rigSetup_Avionic_Std");

                            b1.Property<int?>("trafficLightId")
                                .HasColumnType("integer")
                                .HasColumnName("rigSetup_Avionic_Std_TrafficLightId");

                            b1.HasKey("RigSetuprigRequestId");

                            b1.ToTable("RigSetup");

                            b1.WithOwner()
                                .HasForeignKey("RigSetuprigRequestId");
                        });

                    b.OwnsOne("TyphoonTaskingTool.Components.RigRequestSetupField", "rigSetup_Geo_Location", b1 =>
                        {
                            b1.Property<Guid>("RigSetuprigRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .HasColumnType("text")
                                .HasColumnName("rigSetup_Geo_Location");

                            b1.Property<int?>("trafficLightId")
                                .HasColumnType("integer")
                                .HasColumnName("rigSetup_Geo_Location_TrafficLightId");

                            b1.HasKey("RigSetuprigRequestId");

                            b1.ToTable("RigSetup");

                            b1.WithOwner()
                                .HasForeignKey("RigSetuprigRequestId");
                        });

                    b.OwnsOne("TyphoonTaskingTool.Components.RigRequestSetupField", "rigSetup_Patching", b1 =>
                        {
                            b1.Property<Guid>("RigSetuprigRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .HasColumnType("text")
                                .HasColumnName("rigSetup_Patching");

                            b1.Property<int?>("trafficLightId")
                                .HasColumnType("integer")
                                .HasColumnName("rigSetup_Patching_TrafficLightId");

                            b1.HasKey("RigSetuprigRequestId");

                            b1.ToTable("RigSetup");

                            b1.WithOwner()
                                .HasForeignKey("RigSetuprigRequestId");
                        });

                    b.OwnsOne("TyphoonTaskingTool.Components.RigRequestSetupField", "rigSetup_Radar_Software", b1 =>
                        {
                            b1.Property<Guid>("RigSetuprigRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .HasColumnType("text")
                                .HasColumnName("rigSetup_Radar_Software");

                            b1.Property<int?>("trafficLightId")
                                .HasColumnType("integer")
                                .HasColumnName("rigSetup_Radar_Software_TrafficLightId");

                            b1.HasKey("RigSetuprigRequestId");

                            b1.ToTable("RigSetup");

                            b1.WithOwner()
                                .HasForeignKey("RigSetuprigRequestId");
                        });

                    b.Navigation("request");

                    b.Navigation("rigSetup_Avionic_Std")
                        .IsRequired();

                    b.Navigation("rigSetup_Geo_Location")
                        .IsRequired();

                    b.Navigation("rigSetup_Patching")
                        .IsRequired();

                    b.Navigation("rigSetup_Radar_Software")
                        .IsRequired();
                });

            modelBuilder.Entity("TyphoonTaskingTool.Models.LookupRank", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("TyphoonTaskingTool.Models.LookupStatus", b =>
                {
                    b.Navigation("RequestUpdates");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("TyphoonTaskingTool.Models.LookupTeam", b =>
                {
                    b.Navigation("RequestUpdates");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("TyphoonTaskingTool.Models.LookupUnit", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("TyphoonTaskingTool.Models.Request", b =>
                {
                    b.Navigation("RequestUpdates");
                });
#pragma warning restore 612, 618
        }
    }
}
