// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TyphoonTaskingTool.Data;

#nullable disable

namespace TyphoonTaskingTool.Migrations.Database
{
    [DbContext(typeof(TmscDbContext))]
    [Migration("20260215135259_initial_Db_Commit_postgresql")]
    partial class initial_Db_Commit_postgresql
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TyphoonTaskingTool.Models.LookupRank", b =>
                {
                    b.Property<int>("RankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Rank_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RankId"));

                    b.Property<string>("RankNameLong")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Rank_NameLong");

                    b.Property<string>("RankNameShort")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Rank_NameShort");

                    b.Property<string>("RankNatoequiv")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Rank_NATOEquiv");

                    b.HasKey("RankId");

                    b.ToTable("LOOKUP_Rank", (string)null);
                });

            modelBuilder.Entity("TyphoonTaskingTool.Models.LookupStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Status_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StatusId"));

                    b.Property<string>("StatusDescription")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("Status_Description");

                    b.Property<string>("StatusName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Status_Name");

                    b.HasKey("StatusId");

                    b.ToTable("LOOKUP_Status", (string)null);
                });

            modelBuilder.Entity("TyphoonTaskingTool.Models.LookupTeam", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Team_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TeamId"));

                    b.Property<string>("TeamNameLong")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("Team_NameLong");

                    b.Property<string>("TeamNameShort")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Team_NameShort");

                    b.HasKey("TeamId");

                    b.ToTable("LOOKUP_Team", (string)null);
                });

            modelBuilder.Entity("TyphoonTaskingTool.Models.LookupUnit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Unit_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UnitId"));

                    b.Property<string>("UnitNameLong")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("Unit_NameLong");

                    b.Property<string>("UnitNameShort")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Unit_NameShort");

                    b.HasKey("UnitId");

                    b.ToTable("LOOKUP_Unit", (string)null);
                });

            modelBuilder.Entity("TyphoonTaskingTool.Models.Request", b =>
                {
                    b.Property<Guid>("RequestTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Request_TaskId")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int?>("RankId")
                        .HasColumnType("integer")
                        .HasColumnName("Rank_Id");

                    b.Property<bool?>("RequestArchive")
                        .HasColumnType("boolean")
                        .HasColumnName("Request_Archive");

                    b.Property<string>("RequestContactPhone")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("Request_ContactPhone");

                    b.Property<DateTime?>("RequestCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Request_Created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("RequestEmailAdd")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("Request_EmailAdd");

                    b.Property<string>("RequestFirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Request_FirstName");

                    b.Property<string>("RequestLastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Request_LastName");

                    b.Property<string>("RequestShortId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("Request_ShortId");

                    b.Property<string>("RequestTaskDescription")
                        .HasColumnType("text")
                        .HasColumnName("Request_TaskDescription");

                    b.Property<string>("RequestTitle")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("Request_Title");

                    b.Property<int?>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("Status_Id");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("Team_Id");

                    b.Property<int?>("UnitId")
                        .HasColumnType("integer")
                        .HasColumnName("Unit_Id");

                    b.HasKey("RequestTaskId");

                    b.HasIndex("RankId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TeamId");

                    b.HasIndex("UnitId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("TyphoonTaskingTool.Models.RequestUpdate", b =>
                {
                    b.Property<Guid>("UpdateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Update_Id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("RequestTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("Request_TaskId");

                    b.Property<int?>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("Status_Id");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Update_By");

                    b.Property<string>("UpdateDescription")
                        .HasColumnType("text")
                        .HasColumnName("Update_Description");

                    b.Property<DateTime?>("UpdateTimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Update_TimeStamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UpdateId");

                    b.HasIndex("RequestTaskId");

                    b.HasIndex("StatusId");

                    b.ToTable("RequestUpdates");
                });

            modelBuilder.Entity("TyphoonTaskingTool.Models.Request", b =>
                {
                    b.HasOne("TyphoonTaskingTool.Models.LookupRank", "Rank")
                        .WithMany("Requests")
                        .HasForeignKey("RankId")
                        .HasConstraintName("FK_Request_Rank");

                    b.HasOne("TyphoonTaskingTool.Models.LookupStatus", "Status")
                        .WithMany("Requests")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("FK_Request_Status");

                    b.HasOne("TyphoonTaskingTool.Models.LookupTeam", "Team")
                        .WithMany("Requests")
                        .HasForeignKey("TeamId")
                        .HasConstraintName("FK_Request_Team");

                    b.HasOne("TyphoonTaskingTool.Models.LookupUnit", "Unit")
                        .WithMany("Requests")
                        .HasForeignKey("UnitId")
                        .HasConstraintName("FK_Request_Unit");

                    b.Navigation("Rank");

                    b.Navigation("Status");

                    b.Navigation("Team");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("TyphoonTaskingTool.Models.RequestUpdate", b =>
                {
                    b.HasOne("TyphoonTaskingTool.Models.Request", "RequestTask")
                        .WithMany("RequestUpdates")
                        .HasForeignKey("RequestTaskId")
                        .IsRequired()
                        .HasConstraintName("FK_UpdateRequest");

                    b.HasOne("TyphoonTaskingTool.Models.LookupStatus", "Status")
                        .WithMany("RequestUpdates")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("FK_UpdateStatus");

                    b.Navigation("RequestTask");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TyphoonTaskingTool.Models.LookupRank", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("TyphoonTaskingTool.Models.LookupStatus", b =>
                {
                    b.Navigation("RequestUpdates");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("TyphoonTaskingTool.Models.LookupTeam", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("TyphoonTaskingTool.Models.LookupUnit", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("TyphoonTaskingTool.Models.Request", b =>
                {
                    b.Navigation("RequestUpdates");
                });
#pragma warning restore 612, 618
        }
    }
}
